# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7766f4b063d1073eed8ea3fbc462c30ee82057f6b999cbe32ebc6f22ed309056b57c16fc5ad88a0bd89b04afe223f0f03a4770e9ebda954cba284876d7153c8a

test:
  secret_key_base: 80bd454e893c10e3bee1d3996e153b3089481cc5464a89a2d71861da59a83afb0df0f42512e8ea80b724409aefe46d28450c7fd3de3fe9a0c1aad7c26b186443

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
